#!/bin/bash
F="src/components/SectionProperties.tsx"

sed -i 's/Wealth <br \/>/Warehousing <br \/>/g' "$F"
sed -i 's/Autopilot<\/span>/Distribution<\/span>/g' "$F"
sed -i 's/Military-grade asset management. We combine forensic tenant vetting/Secure, scalable, and intelligent warehousing solutions. We combine advanced inventory tracking/g' "$F"
sed -i 's/with high-frequency yield optimization technology./with high-efficiency distribution technology./g' "$F"

sed -i 's/Yield Simulator/Capacity Simulator/g' "$F"
sed -i 's/Target: Aggressive Short-Let/Target: Cross-Docking \& Storage/g' "$F"
sed -i 's/Investment Capital/Monthly Volume (TEU)/g' "$F"
sed -i 's/KES {/TEU {/g' "$F"
sed -i 's/return `KES ${val/return `TEU ${val/g' "$F"
sed -i 's/Projected Annual Return/Projected Cost Savings/g' "$F"
sed -i 's/8% - 14% Blended Yield/12% - 18% Logistics Optimization/g' "$F"
sed -i 's/Total Yield:/Cost Reduction:/g' "$F"

sed -i 's/Active Portfolio (Live)/Active Facilities (Live)/g' "$F"
sed -i 's/Kilimani Heights/Nairobi ICD/g' "$F"
sed -i 's/Penthouse 4A • Cross-Docking/Bay 4A • Cross-Docking/g' "$F"
sed -i 's/Westlands TC/Mombasa Portside/g' "$F"
sed -i 's/Office 404/Depot 2/g' "$F"
sed -i 's/Diani Yard/Kisumu Transit/g' "$F"
sed -i 's/Yield<\/p>/Efficiency<\/p>/g' "$F"
sed -i 's/Last Payout/Turnover/g' "$F"
sed -i 's/Avg Payout/Turnover/g' "$F"
sed -i 's/KES 120k/12k TEU/g' "$F"
sed -i 's/KES 450k/45k TEU/g' "$F"
sed -i 's/KES 800k/80k TEU/g' "$F"

sed -i 's/Forensic Vetting/Inventory Tracking/g' "$F"
sed -i 's/We don'"'"'t just check credit. We analyze employment stability, criminal history, and freight references. < 5% acceptance rate./We don'"'"'t just store goods. We analyze turnover rates, supply levels, and dispatch efficiency. 99.9% inventory accuracy./g' "$F"
sed -i 's/Proactive Maint./Predictive Flow/g' "$F"
sed -i 's/Automated repair workflows. Issues are detected and resolved before they become expensive liabilities./Automated routing workflows. Bottlenecks are detected and resolved before they impact your supply chain./g' "$F"
sed -i 's/Legal Shield/Secure Storage/g' "$F"
sed -i 's/Ironclad lease agreements drafted by top attorneys. Full eviction protection and insurance coverage included./Ironclad security protocols. 24\/7 CCTV surveillance, biometric access, and full insurance coverage included./g' "$F"
sed -i 's/Yield Optimization/Fulfillment Speed/g' "$F"
sed -i 's/Dynamic pricing algorithms for short-term lets and aggressive rate reviews for long-term leases./Dynamic allocation algorithms for short-term cross-docking and high-density long-term storage./g' "$F"

sed -i 's/Stop Worrying About Tenants./Stop Worrying About Inventory./g' "$F"
sed -i 's/Switch to JBMWealth Autopilot today./Switch to JBM Smart Warehousing today./g' "$F"
sed -i 's/Request Management Proposal/Request Warehousing Proposal/g' "$F"
