#!/bin/bash
F="src/components/SectionLand.tsx"

sed -i 's/Secure <br \/>/Global <br \/>/g' "$F"
sed -i 's/Horizons/Transit/g' "$F"
sed -i 's/• VERIFIED TITLE • READY •/• LIVE TRACKING • SECURE •/g' "$F"
sed -i 's/Land is the foundation of wealth. We offer a curated portfolio of/Reliable logistics is the engine of trade. We offer a secure portfolio of/g' "$F"
sed -i 's/verified title deeds/dedicated freight fleets/g' "$F"
sed -i 's/Title Ready/GPS Tracked/g' "$F"
sed -i 's/Beacons Placed/Live Monitored/g' "$F"
sed -i 's/Perimeter Fenced/Secure Depots/g' "$F"
sed -i 's/Water On Site/Cold Storage/g' "$F"
sed -i 's/Electricity Connected/24\/7 Dispatch/g' "$F"
sed -i 's/Zoned Ground Transport/Cross-Border Ready/g' "$F"
sed -i 's/Mt. Kenya Views/Cross-Border Freight/g' "$F"
sed -i 's/Prime 5-acre blocks available immediately. Perfect for holiday/Dedicated heavy-duty fleets available immediately. Perfect for bulk cargo and regional distribution. Direct port access./g' "$F"
sed -i 's/warehouses or distribution ventures. Direct tarmac access.//g' "$F"
sed -i 's/Browse Catalogue/View Fleet Network/g' "$F"
sed -i 's/All Land/All Fleets/g' "$F"
sed -i 's/Agricultural/Cold Chain/g' "$F"
sed -i 's/Ground Transport/Heavy Haulage/g' "$F"
sed -i 's/Nanyuki Highlands/Refrigerated Trucks/g' "$F"
sed -i 's/Runda Grove/Flatbed Trailers/g' "$F"
sed -i 's/Mixed Use/Container Freight/g' "$F"
sed -i 's/Tigoni Tea/Intermodal Units/g' "$F"
sed -i 's/Hospitality/Last Mile/g' "$F"
sed -i 's/Kilifi Ocean/Delivery Vans/g' "$F"
sed -i 's/titleType: "Title"/titleType: "Insured"/g' "$F"
