#!/bin/bash

FILES="src/components/*.tsx src/App.tsx"

for f in $FILES; do
  sed -i 's/LUXTENPROPERTIES/LUXTEN LOGISTICS/g' "$f"
  sed -i 's/LUXTENProperties/LUXTEN Logistics/g' "$f"
  sed -i 's/Real Estate/Logistics \& Freight/g' "$f"
  sed -i 's/REAL ESTATE/LOGISTICS \& FREIGHT/g' "$f"
  sed -i 's/Real estate/Logistics/g' "$f"
  sed -i 's/Art of Living/Supply Chain/g' "$f"
  sed -i 's/Art Of Living/Supply Chain/g' "$f"
  sed -i 's/Art of<br \/>Living/Supply<br \/>Chain/g' "$f"
  sed -i 's/Art Of <br \/> Living/Supply <br \/> Chain/g' "$f"
  sed -i 's/Land Bank/Global Fleet/g' "$f"
  sed -i 's/Commercial/Freight Hubs/g' "$f"
  sed -i 's/Managers/Warehousing/g' "$f"
  sed -i 's/Capital/Fulfillment/g' "$f"
  sed -i 's/Market/Global Trade/g' "$f"
  sed -i 's/Insights/Analytics/g' "$f"
  
  sed -i 's/luxury living/global trade/g' "$f"
  sed -i 's/visionary development/visionary logistics/g' "$f"
  sed -i 's/bespoke management/bespoke freight management/g' "$f"
  sed -i 's/finest properties/most efficient routes/g' "$f"
  sed -i 's/Curated homes/Optimized routing/g' "$f"
  sed -i 's/turn-key luxury villas/turn-key freight/g' "$f"
  sed -i 's/smart city apartments/smart city delivery/g' "$f"
  sed -i 's/Penthouse/Distribution Center/g' "$f"
  sed -i 's/Luxury Villa/Freight Hub/g' "$f"
  sed -i 's/Apartment/Sortation Facility/g' "$f"
  sed -i 's/Private Estate/Fleet Yard/g' "$f"
  sed -i 's/Safari Lodge/Regional Depot/g' "$f"
  sed -i 's/Conservation/Transit Network/g' "$f"
  sed -i 's/Safari Camp/Cross-Dock/g' "$f"
  sed -i 's/Boutique Hotel/Logistics Park/g' "$f"
  sed -i 's/Beachfront/Port Terminal/g' "$f"
  sed -i 's/4 BDR/50,000 SQFT/g' "$f"
  sed -i 's/6 BDR/120,000 SQFT/g' "$f"
  sed -i 's/3 BDR/30,000 SQFT/g' "$f"
  sed -i 's/15 SUITES/20 BAYS/g' "$f"
  sed -i 's/10 TENTS/15 BAYS/g' "$f"
  sed -i 's/6 VILLAS/4 WAREHOUSES/g' "$f"
  
  sed -i 's/Residential/Ground Transport/g' "$f"
  sed -i 's/Buy/Ship/g' "$f"
  sed -i 's/Sell/Track/g' "$f"
  sed -i 's/Rent/Store/g' "$f"
  sed -i 's/Develop/Scale/g' "$f"
  sed -i 's/Explore & Furnish with A.I./Explore Routes with A.I./g' "$f"
done
